#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend topnature.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 178161-web-01 100.25.14.47:80
        server 178161-web-02 54.146.86.37:80
' >> /etc/haproxy/haproxt.cfg

# Restart HAproxy service
service haproxy restart
